name: Arena
main: com.gmail.jpk.stu.arena.ArenaPlugin
version: 0.5.7
authors: [Kody104, ASquanchyPenguin]

commands:
    arena:
      description: Runs various tasks for the Arena.
      usage: /arena -[cc|csi|fr|spawn|round|xp|lvl] -(subtask)
      permission: Arena.mod.arena
      permission-message: You don't have permission.
    ch:
      description: Messages the player's channel or used to toggle channel lock.
      usage: /ch (-lock) [message]
      permission: Arena.ch
      permission-message: You don't have permission.
    chsys:
      description: Runs various tasks for the ChatSystem.
      usage: /chsys [role|remove|debug|color|set] (value) (value)
      permission: Arena.mod.chsys
      permission-message: You don't have permission.
    gci:
      description: Gives an ArenaPlayer a SpecialItem
      usage: /gci [item] [target-player] (quantity)
      aliases: [givecustomitem]
      permission: Arena.mod.gci
      permission-message: You don't have permission.
    gai:
      description: Gives an player an AbilityItem
      usage: /gai [ability] [target-player]
      aliases: [giveabilityitem]
      permission: Arena.mod.gai
      permission-message: You don't have permission.
    join:
      description: Enters player into the arena.
      usage: /join
      permission: Arena.join
      permission-message: You don't have permission.
    leave:
      description: Remove player from the arena.
      usage: /leave
      permission: Arena.leave
      permission-message: You don't have permission.
    ready:
      description: Allows the player to ready themselves for battle.
      usage: /ready
      permission: Arena.ready
      permission-message: You don't have permission.
    role:
      description: Allows a player to view their current role, see all roles, or get info about a specific roles.
      usage: /role [role|help|all] <role>
      permission: Arena.role
      permission-message: You don't have permission.
    quit:
      description: Quits a player's role (if any).
      usage: /quit
      permission: Arena.quit
      permission-message: You don't have permission.